[Network]
topology = DragonflyChipletFC
k_node = 3
routing_algorithm = MIN
internal_bandwidth = 1
external_latency = 8
mis_routing = false
buffer_size = 32
vc_number = 3

[Workload]
traffic = uniform
traffic_scale = 0
packet_length = 4

[Simulation]
injection_increment = 0.01
simulation_time = 10000
timeout_threshold = 500
timeout_limit = 100
threads = 2

[Files]
output_file = ../../output/output_fc_k3_uniform.csv
log_file = ../../output/log_fc_k3.txt

; [Network]
; topology = MultiChipMesh
; routing_algorithm = XY
; k_node = 2
; k_chip = 2
; buffer_size = 20
; vc_number = 2
; # d2d_IF = off_chip_parallel
; d2d_IF = off_chip_serial

; [Workload]
; traffic = uniform

; [Simulation]
; injection_increment = 0.05

; [Files]
; netrace_file = ../../input/netrace/blackscholes_64c_simsmall.tra.bz2
; #netrace_file = ../../input/netrace/bodytrack_64c_simlarge.tra.bz2
; #netrace_file = ../../input/netrace/canneal_64c_simmedium.tra.bz2
; #netrace_file = ../../input/netrace/dedup_64c_simmedium.tra.bz2
; #netrace_file = ../../input/netrace/ferret_64c_simmedium.tra.bz2
; #netrace_file = ../../input/netrace/fluidanimate_64c_simsmall.tra.bz2
; #netrace_file = ../../input/netrace/swaptions_64c_simlarge.tra.bz2
; #netrace_file = ../../input/netrace/vips_64c_simmedium.tra.bz2
; #netrace_file = ../../input/netrace/x264_64c_simsmall.tra.bz2

